### ISSUE TITLE
NoMethodError - undefined method 'this'

### ISSUE THREAD

**Issue by jcw-** [appfolio/rails5_xhr_update#5]
I appear to be unable to run this, any thoughts?

Installed via:
`gem install rails5_xhr_update`

Ran via:
`git grep -l "xhr :" | rails5_xhr_update --write`

Results in:
```
/Users/jcw/.rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/rubygems/specification.rb:2162:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fca8f44c50c rails5_xhr_update-0.5.0> (NoMethodError)
	from /Users/jcw/.rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/rubygems/specification.rb:1060:in `find_active_stub_by_path'
	from /Users/jcw/.rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/jcw/.rvm/gems/ruby-2.3.7/gems/rails5_xhr_update-0.5.0/lib/rails5_xhr_update.rb:3:in `<top (required)>'
	from /Users/jcw/.rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /Users/jcw/.rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /Users/jcw/.rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/jcw/.rvm/gems/ruby-2.3.7/gems/rails5_xhr_update-0.5.0/bin/rails5_xhr_update:4:in `<top (required)>'
	from /Users/jcw/.rvm/gems/ruby-2.3.7/bin/rails5_xhr_update:22:in `load'
	from /Users/jcw/.rvm/gems/ruby-2.3.7/bin/rails5_xhr_update:22:in `<main>'
	from /Users/jcw/.rvm/gems/ruby-2.3.7/bin/ruby_executable_hooks:24:in `eval'
	from /Users/jcw/.rvm/gems/ruby-2.3.7/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by jcw-** [comment]
I was able to get this working by making a new gemset:

```
rvm gemset create test1
rvm gemset use test1
```

and then running the steps above again...
